title: "Amalore Nambi"
name: "Marie Amalore Nambi"
description: "Academic webpage"

url: "https://amalore.github.io"   # IMPORTANT
baseurl: ""                             # keep empty

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "aqua"

author:
  name: "Marie Amalore Nambi"   # FIXED
  avatar: "/images/profile.png"
  bio: "Postdoctoral Researcher, Sabancı University"
  location: "Istanbul, Turkey"
  email: "amalore.p@gmail.com"
  links:
    
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Amalore"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=MZbDLuIAAAAJ&hl=en"
      - label: "Scopus"
      icon: "ai ai-scopus"
      url: "https://www.scopus.com/authid/detail.uri?authorId=57902619400#"

include:
  - _pages

plugins:
  - jekyll-include-cache
